{{
    config(
        materialized='incremental',
        incremental_strategy='append',
        pre_hook=["DELETE FROM ecom_project.silver_sc.customer_silver_data WHERE PERD_END_DT=(SELECT BUS_DATE FROM ECOM_PROJECT.SILVER_SC.T_APPL_DT_C)"]
        
    
    )
}}


WITH GET_BUS_DATE AS 
( SELECT BUS_DATE as PERD_END_DT FROM ECOM_PROJECT.SILVER_SC.T_APPL_DT_C )
,

CUSTOMER_CLEANS_DATA AS 
(
select 
TRIM(REGEXP_REPLACE(CUSTOMER_ID,'[^0-9]')) as CUST_ID,
TRIM(INITCAP(FIRST_NAME)) AS CUST_FIRST_NAME,
TRIM(INITCAP(LAST_NAME)) AS CUST_LAST_NAME,
TRIM(UPPER(EMAIL)) AS EMAIL,
'+91-'||TRIM(PHONE) AS PHONE_NUMBER,
UPPER(STATE) AS STATE_NAME,
TRIM(UPPER(CITY)) AS CITY_NAME,
CASE STATE
        WHEN 'Karnataka' THEN 'KA'
        WHEN 'Maharashtra' THEN 'MH'
        WHEN 'Delhi' THEN 'DL'
        WHEN 'Tamil Nadu' THEN 'TN'
        WHEN 'Gujarat' THEN 'GJ'
        ELSE 'Other State / Unknown'
    END AS STATE_CODE,
    TRIM(UPPER(LOYALTY_TIER)) AS LOYALTY_TIER_TAGS,
    REGISTRATION_DATE AS RAW_DATE,
    TO_CHAR(TO_DATE(REGISTRATION_DATE),'DD-MM-YYYY') AS REGISTRATION_DATE,
    TO_CHAR(TO_DATE(REGISTRATION_DATE),'YYYY') AS YEAR_OF_REGISTRATION,
    TO_CHAR(TO_DATE(REGISTRATION_DATE),'DD') AS DATE_OF_REGISTRATION,
    DATEDIFF(YEAR,REGISTRATION_DATE,CURRENT_DATE) AS DATE_DIFF
from {{ source('ecom', 'customers_raw_data') }} 
)
SELECT * FROM  GET_BUS_DATE,CUSTOMER_CLEANS_DATA

